exports.RESPONSE_TITLES = {
  ERROR: "Error",
  UNAUTHORIZED: "Unauthorize",
  SUCCESS: "Success",
  NOT_FOUND: "Not Found",
  DB_ERROR: "Error In Database",
  FILE_ERROR: "Error In File Uploaded",
  EXPIRED: "Token Expired",
  TOKEN_EXPIRED: "TokenExpiredError",
  CODE_GENERATED: "Code Generated",
};

exports.HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  DELETE_SUCCESS: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOW: 405,
  CONFLICT: 409,
  INTERNAL_SERVER: 500,
};

exports.MESSAGE = {
  FILE_NOT_FOUND: "No File Exists With This Name or URL",
  FILE_DELETED: "File Successfully Deleted",
  USER_LOGGEDIN_SUCCESSFULLY: "User Signed In successfully",
  USER_REGISTERED_SUCCESSFULLY: "User Registered In successfully",
  SUCCESSFUL: "successful",
  DELETE_SUCCESS: "Successfully Deleted",
  INITES_SENT: "Invites Sent Successfully",
  INCOMPLETE_INFORMATION: "Please Provide Complete Information",
  USER_NOT_FOUND: "Not Found",
  INVALID_CREDENTIALS: "Invalid credentials",
  INVALID_PASSWORD: "Invalid Password",
  USER_LOG_OUT: "User Logged Out Successfully",
  INTERNAL_ERR0R: "Internal Server Error Occured",
  DUPLICATE_RECORD: "This Record is Duplicated",
  NOT_AUTHORIZED: "You Are Not Authorized",
  BAD_REQUEST: "Bad Request",
  NOT_LOGGED_IN: "You are not logged in! Please login in to continue",
  RESPONSE_SUCCESS: "Data found successfully",
  DATA_UPDATED: "Data updated successfully",
  DATA_NOT_FOUND: "Data not found",
  DATA_DELETED: "Data deleted successfully",
  INCORRECT_PASSWORD: "Current Password is Incorrect",
  INVALID_FILE: "Error While Processing The File",
  JWT_EXPIRED: "JWT Token Has Expired",
  CODE_NOT: "Code Is Invalid",
  CODE_GENERATED: "Code Has Been Sent To Your Email",
  FOLDER_NOT_FOUND: "Folder Not Fond",
  FILE_NOT_FOUND: "File Not Fond",
  FAILED_TO_CREATE_FOLDER: "Failed to create a new folder",
  FAILED_TO_UPDATE_FOLDER: "Failed to update the folder",
  FAILED_TO_MOVE_FILE: "Failed to move the file",
  FAILED_TO_SHARE_FILE: "Failed to share the file",
};
